version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
      - image: ftps_server
    steps:
      - run:
          name: 'Install Container Dependancies'
          command: |
            apt update && apt install -y python3 python3-pip python3-venv git curl
      - checkout
      - run:
          name: 'Install Docker client'
          command: |
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: 'Smoke Tests'
          command: |
            python3 ./tests/smoke_tests localhost

workflows:
  version: 2
  commit:
    jobs:
      - build
  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
